
perguntas_por_nivel_e_disciplina = {
    "1° Ano": {
        "Matemática": [
            {"pergunta": "Quanto é 2 + 2?", "opcoes": ["3", "4", "5", "6"], "resposta": 1},
            {"pergunta": "Quanto é 3 + 3?", "opcoes": ["5", "6", "7", "8"], "resposta": 1},
            {"pergunta": "Quanto é 1 + 1?", "opcoes": ["1", "2", "3", "4"], "resposta": 1},
            {"pergunta": "Quanto é 4 - 1?", "opcoes": ["2", "3", "4", "5"], "resposta": 1},
            {"pergunta": "Quanto é 5 - 2?", "opcoes": ["2", "3", "4", "5"], "resposta": 1},
            {"pergunta": "Quanto é 6 + 1?", "opcoes": ["6", "7", "8", "9"], "resposta": 1},
            {"pergunta": "Quanto é 3 - 1?", "opcoes": ["1", "2", "3", "4"], "resposta": 1},
            {"pergunta": "Quanto é 7 - 5?", "opcoes": ["1", "2", "3", "4"], "resposta": 1},
            {"pergunta": "Quanto é 9 - 3?", "opcoes": ["5", "6", "7", "8"], "resposta": 1},
            {"pergunta": "Quanto é 8 + 1?", "opcoes": ["8", "9", "10", "11"], "resposta": 1},
        ],
        "Língua Portuguesa": [
            {"pergunta": "Qual é a letra inicial da palavra 'gato'?", "opcoes": ["A", "B", "G", "D"], "resposta": 2},
            {"pergunta": "Qual é a letra inicial da palavra 'casa'?", "opcoes": ["C", "B", "G", "D"], "resposta": 0},
            {"pergunta": "Qual é a última letra da palavra 'cavalo'?", "opcoes": ["A", "O", "V", "L"], "resposta": 1},
            {"pergunta": "Qual a letra inicial da palavra 'livro'?", "opcoes": ["L", "I", "V", "R"], "resposta": 0},
            {"pergunta": "Qual a letra inicial da palavra 'escola'?", "opcoes": ["E", "S", "C", "L"], "resposta": 0},
            {"pergunta": "Qual a última letra da palavra 'elefante'?", "opcoes": ["E", "T", "N", "F"], "resposta": 0},
            {"pergunta": "Qual a letra inicial da palavra 'menino'?", "opcoes": ["M", "E", "N", "I"], "resposta": 0},
            {"pergunta": "Qual a última letra da palavra 'borboleta'?", "opcoes": ["A", "E", "T", "L"], "resposta": 0},
            {"pergunta": "Qual a letra inicial da palavra 'girafa'?", "opcoes": ["G", "I", "R", "A"], "resposta": 0},
            {"pergunta": "Qual a letra inicial da palavra 'árvore'?", "opcoes": ["Á", "R", "V", "O"], "resposta": 0},
        ],
        "Ciências": [
            {"pergunta": "Qual desses animais pode voar?", "opcoes": ["Cachorro", "Gato", "Pássaro", "Peixe"], "resposta": 2},
            {"pergunta": "Qual parte da planta é responsável pela fotossíntese?", "opcoes": ["Raiz", "Folha", "Flor", "Semente"], "resposta": 1},
            {"pergunta": "Qual destes animais é um mamífero?", "opcoes": ["Cobra", "Gato", "Sapo", "Galinha"], "resposta": 1},
            {"pergunta": "Qual parte da planta absorve água?", "opcoes": ["Folha", "Raiz", "Flor", "Semente"], "resposta": 1},
            {"pergunta": "Qual destes é um inseto?", "opcoes": ["Peixe", "Sapo", "Borboleta", "Cachorro"], "resposta": 2},
            {"pergunta": "O que a vaca nos dá?", "opcoes": ["Leite", "Ovos", "Carne", "Lã"], "resposta": 0},
            {"pergunta": "Qual desses é um animal doméstico?", "opcoes": ["Leão", "Tigre", "Gato", "Elefante"], "resposta": 2},
            {"pergunta": "Qual é o estado da água em temperatura ambiente?", "opcoes": ["Sólido", "Líquido", "Gasoso", "Plasma"], "resposta": 1},
            {"pergunta": "Qual é o órgão responsável pela respiração?", "opcoes": ["Coração", "Pulmão", "Fígado", "Estômago"], "resposta": 1},
            {"pergunta": "Qual destes é um corpo celeste?", "opcoes": ["Árvore", "Montanha", "Sol", "Rio"], "resposta": 2},
        ],
        "História": [
            {"pergunta": "Quem foi o primeiro presidente do Brasil?", "opcoes": ["Getúlio Vargas", "Juscelino Kubitschek", "Deodoro da Fonseca", "Dom Pedro II"], "resposta": 2},
            {"pergunta": "Em que ano o Brasil foi descoberto?", "opcoes": ["1492", "1500", "1600", "1700"], "resposta": 1},
            {"pergunta": "Quem descobriu o Brasil?", "opcoes": ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], "resposta": 1},
            {"pergunta": "O que eram as capitanias hereditárias?", "opcoes": ["Divisões administrativas no Brasil Colônia", "Tipos de plantações", "Grupos de indígenas", "Territórios na África"], "resposta": 0},
            {"pergunta": "Quem proclamou a independência do Brasil?", "opcoes": ["Dom Pedro I", "Dom Pedro II", "Tiradentes", "Deodoro da Fonseca"], "resposta": 0},
            {"pergunta": "Quem foi Tiradentes?", "opcoes": ["Um pintor", "Um médico", "Um dentista e herói da Inconfidência Mineira", "Um presidente"], "resposta": 2},
            {"pergunta": "O que é uma aldeia indígena?", "opcoes": ["Um grupo de animais", "Um grupo de casas onde vivem indígenas", "Uma cidade grande", "Um tipo de planta"], "resposta": 1},
            {"pergunta": "O que é uma bandeira?", "opcoes": ["Um símbolo de um país", "Uma planta", "Um animal", "Uma montanha"], "resposta": 0},
            {"pergunta": "O que é um museu?", "opcoes": ["Um lugar onde se guardam objetos históricos", "Uma escola", "Um hospital", "Um parque"], "resposta": 0},
            {"pergunta": "Quem foi Zumbi dos Palmares?", "opcoes": ["Um líder indígena", "Um líder dos escravos", "Um presidente", "Um artista"], "resposta": 1},
        ],
        "Geografia": [
            {"pergunta": "Qual é o maior continente?", "opcoes": ["África", "América", "Ásia", "Europa"], "resposta": 2},
            {"pergunta": "Qual é o menor continente?", "opcoes": ["África", "Oceania", "Antártica", "Europa"], "resposta": 1},
            {"pergunta": "Qual é o maior oceano?", "opcoes": ["Atlântico", "Pacífico", "Índico", "Ártico"], "resposta": 1},
            {"pergunta": "Qual país tem a maior população?", "opcoes": ["Estados Unidos", "Índia", "Brasil", "China"], "resposta": 3},
            {"pergunta": "Qual é o maior país da América do Sul?", "opcoes": ["Argentina", "Brasil", "Chile", "Peru"], "resposta": 1},
            {"pergunta": "Qual desses é um rio brasileiro?", "opcoes": ["Nilo", "Amazonas", "Mississipi", "Danúbio"], "resposta": 1},
            {"pergunta": "Qual é a capital do Brasil?", "opcoes": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "resposta": 2},
            {"pergunta": "Qual é o maior país do mundo?", "opcoes": ["Estados Unidos", "China", "Rússia", "Canadá"], "resposta": 2},
            {"pergunta": "Qual continente está localizado o Brasil?", "opcoes": ["América do Sul", "América do Norte", "Europa", "África"], "resposta": 0},
            {"pergunta": "Qual é o nome do maior deserto do mundo?", "opcoes": ["Sahara", "Atacama", "Gobi", "Kalahari"], "resposta": 0},
        ],
        "Computação": [
            {"pergunta": "Qual dispositivo usamos para digitar?", "opcoes": ["Mouse", "Teclado", "Monitor", "Impressora"], "resposta": 1},
            {"pergunta": "Qual parte do computador mostra as imagens?", "opcoes": ["Mouse", "Teclado", "Monitor", "CPU"], "resposta": 2},
            {"pergunta": "Qual parte do computador armazena informações?", "opcoes": ["Monitor", "Teclado", "Mouse", "HD"], "resposta": 3},
            {"pergunta": "Qual desses é um navegador de internet?", "opcoes": ["Windows", "Word", "Chrome", "Excel"], "resposta": 2},
            {"pergunta": "O que significa a sigla 'CPU'?", "opcoes": ["Central Processing Unit", "Computer Personal Unit", "Central Personal Unit", "Computer Processing Unit"], "resposta": 0},
            {"pergunta": "Qual desses é um sistema operacional?", "opcoes": ["Microsoft Word", "Google Chrome", "Windows", "Excel"], "resposta": 2},
            {"pergunta": "O que é um software?", "opcoes": ["Um programa de computador", "Um hardware", "Um periférico", "Um sistema operacional"], "resposta": 0},
            {"pergunta": "Qual desses dispositivos é de entrada?", "opcoes": ["Monitor", "Impressora", "Teclado", "CPU"], "resposta": 2},
            {"pergunta": "Para que serve o mouse?", "opcoes": ["Digitar", "Selecionar itens na tela", "Armazenar dados", "Exibir imagens"], "resposta": 1},
            {"pergunta": "O que é um vírus de computador?", "opcoes": ["Um hardware", "Um software malicioso", "Um sistema operacional", "Um navegador"], "resposta": 1},
        ],
        "Arte": [
            {"pergunta": "Qual destas é uma cor primária?", "opcoes": ["Verde", "Amarelo", "Roxo", "Laranja"], "resposta": 1},
            {"pergunta": "Qual destes é um material usado para desenhar?", "opcoes": ["Papel", "Lápis", "Tesoura", "Cola"], "resposta": 1},
            {"pergunta": "Qual destes é um artista famoso?", "opcoes": ["Leonardo da Vinci", "Isaac Newton", "Albert Einstein", "Galileu Galilei"], "resposta": 0},
            {"pergunta": "Qual destes é um estilo de dança?", "opcoes": ["Ballet", "Cálculo", "Geometria", "Física"], "resposta": 0},
            {"pergunta": "Qual destes é um instrumento musical?", "opcoes": ["Violino", "Bola", "Livro", "Computador"], "resposta": 0},
            {"pergunta": "O que usamos para pintar?", "opcoes": ["Pincel", "Cola", "Tesoura", "Borracha"], "resposta": 0},
            {"pergunta": "Qual destes é um gênero musical?", "opcoes": ["Rock", "Física", "Matemática", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destas é uma técnica de pintura?", "opcoes": ["Aquarela", "Biologia", "História", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destes é um famoso pintor?", "opcoes": ["Van Gogh", "Einstein", "Newton", "Edison"], "resposta": 0},
            {"pergunta": "Qual destas é uma forma de arte?", "opcoes": ["Escultura", "Cálculo", "Análise", "Pesquisa"], "resposta": 0},
        ]
    },
    "2° Ano": {
        "Matemática": [
            {"pergunta": "Quanto é 4 + 2?", "opcoes": ["6", "7", "8", "9"], "resposta": 0},
            {"pergunta": "Quanto é 5 - 3?", "opcoes": ["1", "2", "3", "4"], "resposta": 1},
            {"pergunta": "Quanto é 3 + 5?", "opcoes": ["7", "8", "9", "10"], "resposta": 1},
            {"pergunta": "Quanto é 10 - 7?", "opcoes": ["2", "3", "4", "5"], "resposta": 1},
            {"pergunta": "Quanto é 6 + 3?", "opcoes": ["8", "9", "10", "11"], "resposta": 1},
            {"pergunta": "Quanto é 8 - 4?", "opcoes": ["2", "3", "4", "5"], "resposta": 2},
            {"pergunta": "Quanto é 7 + 2?", "opcoes": ["8", "9", "10", "11"], "resposta": 1},
            {"pergunta": "Quanto é 5 + 4?", "opcoes": ["8", "9", "10", "11"], "resposta": 1},
            {"pergunta": "Quanto é 9 - 5?", "opcoes": ["3", "4", "5", "6"], "resposta": 1},
            {"pergunta": "Quanto é 6 + 2?", "opcoes": ["7", "8", "9", "10"], "resposta": 1},
        ],
        "Língua Portuguesa": [
            {"pergunta": "Qual é a última letra da palavra 'pato'?", "opcoes": ["A", "O", "T", "P"], "resposta": 1},
            {"pergunta": "Qual palavra rima com 'bola'?", "opcoes": ["Casa", "Gato", "Escola", "Mola"], "resposta": 3},
            {"pergunta": "Qual é o plural de 'cão'?", "opcoes": ["Cães", "Cãos", "Cãeses", "Cãozes"], "resposta": 0},
            {"pergunta": "Qual palavra é um verbo?", "opcoes": ["Correr", "Rápido", "Feliz", "Grande"], "resposta": 0},
            {"pergunta": "Qual destas palavras é um substantivo?", "opcoes": ["Amor", "Bonito", "Rápido", "Feliz"], "resposta": 0},
            {"pergunta": "Qual é o feminino de 'menino'?", "opcoes": ["Menina", "Menino", "Menine", "Menin"], "resposta": 0},
            {"pergunta": "Qual destas palavras é um adjetivo?", "opcoes": ["Grande", "Casa", "Livro", "Mesa"], "resposta": 0},
            {"pergunta": "Qual é o verbo da frase 'Eu corro todos os dias'?", "opcoes": ["Eu", "Corro", "Todos", "Dias"], "resposta": 1},
            {"pergunta": "Qual destas palavras é um pronome?", "opcoes": ["Ele", "Bonito", "Mesa", "Correr"], "resposta": 0},
            {"pergunta": "Qual é o diminutivo de 'cão'?", "opcoes": ["Cãozinho", "Cãos", "Cãezinho", "Cãinho"], "resposta": 0},
        ],
        "Ciências": [
            {"pergunta": "Qual destes é um planeta?", "opcoes": ["Sol", "Lua", "Terra", "Estrela"], "resposta": 2},
            {"pergunta": "O que os peixes usam para respirar?", "opcoes": ["Pulmões", "Brânquias", "Asas", "Narinas"], "resposta": 1},
            {"pergunta": "Qual destes animais é um mamífero?", "opcoes": ["Cobra", "Gato", "Sapo", "Galinha"], "resposta": 1},
            {"pergunta": "Qual parte da planta absorve água?", "opcoes": ["Folha", "Raiz", "Flor", "Semente"], "resposta": 1},
            {"pergunta": "Qual destes é um inseto?", "opcoes": ["Peixe", "Sapo", "Borboleta", "Cachorro"], "resposta": 2},
            {"pergunta": "O que a vaca nos dá?", "opcoes": ["Leite", "Ovos", "Carne", "Lã"], "resposta": 0},
            {"pergunta": "Qual desses é um animal doméstico?", "opcoes": ["Leão", "Tigre", "Gato", "Elefante"], "resposta": 2},
            {"pergunta": "Qual é o estado da água em temperatura ambiente?", "opcoes": ["Sólido", "Líquido", "Gasoso", "Plasma"], "resposta": 1},
            {"pergunta": "Qual é o órgão responsável pela respiração?", "opcoes": ["Coração", "Pulmão", "Fígado", "Estômago"], "resposta": 1},
            {"pergunta": "Qual destes é um corpo celeste?", "opcoes": ["Árvore", "Montanha", "Sol", "Rio"], "resposta": 2},
        ],
        "História": [
            {"pergunta": "Quem foi Tiradentes?", "opcoes": ["Um pintor", "Um médico", "Um dentista e herói da Inconfidência Mineira", "Um presidente"], "resposta": 2},
            {"pergunta": "O que é uma aldeia indígena?", "opcoes": ["Um grupo de animais", "Um grupo de casas onde vivem indígenas", "Uma cidade grande", "Um tipo de planta"], "resposta": 1},
            {"pergunta": "O que é uma bandeira?", "opcoes": ["Um símbolo de um país", "Uma planta", "Um animal", "Uma montanha"], "resposta": 0},
            {"pergunta": "O que é um museu?", "opcoes": ["Um lugar onde se guardam objetos históricos", "Uma escola", "Um hospital", "Um parque"], "resposta": 0},
            {"pergunta": "Quem foi Zumbi dos Palmares?", "opcoes": ["Um líder indígena", "Um líder dos escravos", "Um presidente", "Um artista"], "resposta": 1},
            {"pergunta": "Quem foi o primeiro presidente do Brasil?", "opcoes": ["Getúlio Vargas", "Juscelino Kubitschek", "Deodoro da Fonseca", "Dom Pedro II"], "resposta": 2},
            {"pergunta": "Em que ano o Brasil foi descoberto?", "opcoes": ["1492", "1500", "1600", "1700"], "resposta": 1},
            {"pergunta": "Quem descobriu o Brasil?", "opcoes": ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], "resposta": 1},
            {"pergunta": "O que eram as capitanias hereditárias?", "opcoes": ["Divisões administrativas no Brasil Colônia", "Tipos de plantações", "Grupos de indígenas", "Territórios na África"], "resposta": 0},
            {"pergunta": "Quem proclamou a independência do Brasil?", "opcoes": ["Dom Pedro I", "Dom Pedro II", "Tiradentes", "Deodoro da Fonseca"], "resposta": 0},
        ],
        "Geografia": [
            {"pergunta": "Qual é o maior oceano?", "opcoes": ["Atlântico", "Pacífico", "Índico", "Ártico"], "resposta": 1},
            {"pergunta": "Qual país tem a maior população?", "opcoes": ["Estados Unidos", "Índia", "Brasil", "China"], "resposta": 3},
            {"pergunta": "Qual é o maior país da América do Sul?", "opcoes": ["Argentina", "Brasil", "Chile", "Peru"], "resposta": 1},
            {"pergunta": "Qual desses é um rio brasileiro?", "opcoes": ["Nilo", "Amazonas", "Mississipi", "Danúbio"], "resposta": 1},
            {"pergunta": "Qual é a capital do Brasil?", "opcoes": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "resposta": 2},
            {"pergunta": "Qual é o maior país do mundo?", "opcoes": ["Estados Unidos", "China", "Rússia", "Canadá"], "resposta": 2},
            {"pergunta": "Qual continente está localizado o Brasil?", "opcoes": ["América do Sul", "América do Norte", "Europa", "África"], "resposta": 0},
            {"pergunta": "Qual é o nome do maior deserto do mundo?", "opcoes": ["Sahara", "Atacama", "Gobi", "Kalahari"], "resposta": 0},
            {"pergunta": "Qual é o menor continente?", "opcoes": ["África", "Oceania", "Antártica", "Europa"], "resposta": 1},
            {"pergunta": "Qual é o maior continente?", "opcoes": ["África", "América", "Ásia", "Europa"], "resposta": 2},
        ],
        "Computação": [
            {"pergunta": "Qual parte do computador armazena informações?", "opcoes": ["Monitor", "Teclado", "Mouse", "HD"], "resposta": 3},
            {"pergunta": "Qual desses é um navegador de internet?", "opcoes": ["Windows", "Word", "Chrome", "Excel"], "resposta": 2},
            {"pergunta": "O que significa a sigla 'CPU'?", "opcoes": ["Central Processing Unit", "Computer Personal Unit", "Central Personal Unit", "Computer Processing Unit"], "resposta": 0},
            {"pergunta": "Qual desses é um sistema operacional?", "opcoes": ["Microsoft Word", "Google Chrome", "Windows", "Excel"], "resposta": 2},
            {"pergunta": "O que é um software?", "opcoes": ["Um programa de computador", "Um hardware", "Um periférico", "Um sistema operacional"], "resposta": 0},
            {"pergunta": "Qual desses dispositivos é de entrada?", "opcoes": ["Monitor", "Impressora", "Teclado", "CPU"], "resposta": 2},
            {"pergunta": "Para que serve o mouse?", "opcoes": ["Digitar", "Selecionar itens na tela", "Armazenar dados", "Exibir imagens"], "resposta": 1},
            {"pergunta": "O que é um vírus de computador?", "opcoes": ["Um hardware", "Um software malicioso", "Um sistema operacional", "Um navegador"], "resposta": 1},
            {"pergunta": "Qual dispositivo usamos para digitar?", "opcoes": ["Mouse", "Teclado", "Monitor", "Impressora"], "resposta": 1},
            {"pergunta": "Qual parte do computador mostra as imagens?", "opcoes": ["Mouse", "Teclado", "Monitor", "CPU"], "resposta": 2},
        ],
        "Arte": [
            {"pergunta": "Qual destas é uma cor primária?", "opcoes": ["Verde", "Amarelo", "Roxo", "Laranja"], "resposta": 1},
            {"pergunta": "Qual destes é um material usado para desenhar?", "opcoes": ["Papel", "Lápis", "Tesoura", "Cola"], "resposta": 1},
            {"pergunta": "Qual destes é um artista famoso?", "opcoes": ["Leonardo da Vinci", "Isaac Newton", "Albert Einstein", "Galileu Galilei"], "resposta": 0},
            {"pergunta": "Qual destes é um estilo de dança?", "opcoes": ["Ballet", "Cálculo", "Geometria", "Física"], "resposta": 0},
            {"pergunta": "Qual destes é um instrumento musical?", "opcoes": ["Violino", "Bola", "Livro", "Computador"], "resposta": 0},
            {"pergunta": "O que usamos para pintar?", "opcoes": ["Pincel", "Cola", "Tesoura", "Borracha"], "resposta": 0},
            {"pergunta": "Qual destes é um gênero musical?", "opcoes": ["Rock", "Física", "Matemática", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destas é uma técnica de pintura?", "opcoes": ["Aquarela", "Biologia", "História", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destes é um famoso pintor?", "opcoes": ["Van Gogh", "Einstein", "Newton", "Edison"], "resposta": 0},
            {"pergunta": "Qual destas é uma forma de arte?", "opcoes": ["Escultura", "Cálculo", "Análise", "Pesquisa"], "resposta": 0},
        ]
    },
    "3° Ano": {
        "Matemática": [
            {"pergunta": "Quanto é 7 + 3?", "opcoes": ["10", "11", "12", "13"], "resposta": 0},
            {"pergunta": "Quanto é 10 - 4?", "opcoes": ["5", "6", "7", "8"], "resposta": 1},
            {"pergunta": "Quanto é 8 + 2?", "opcoes": ["9", "10", "11", "12"], "resposta": 1},
            {"pergunta": "Quanto é 15 - 6?", "opcoes": ["7", "8", "9", "10"], "resposta": 2},
            {"pergunta": "Quanto é 9 + 4?", "opcoes": ["11", "12", "13", "14"], "resposta": 2},
            {"pergunta": "Quanto é 12 - 7?", "opcoes": ["4", "5", "6", "7"], "resposta": 1},
            {"pergunta": "Quanto é 11 + 2?", "opcoes": ["12", "13", "14", "15"], "resposta": 1},
            {"pergunta": "Quanto é 13 - 5?", "opcoes": ["7", "8", "9", "10"], "resposta": 1},
            {"pergunta": "Quanto é 14 + 1?", "opcoes": ["14", "15", "16", "17"], "resposta": 1},
            {"pergunta": "Quanto é 16 - 8?", "opcoes": ["6", "7", "8", "9"], "resposta": 2},
        ],
        "Língua Portuguesa": [
            {"pergunta": "Qual é o plural de 'cão'?", "opcoes": ["Cães", "Cãos", "Cãeses", "Cãozes"], "resposta": 0},
            {"pergunta": "Qual palavra é um verbo?", "opcoes": ["Correr", "Rápido", "Feliz", "Grande"], "resposta": 0},
            {"pergunta": "Qual destas palavras é um substantivo?", "opcoes": ["Amor", "Bonito", "Rápido", "Feliz"], "resposta": 0},
            {"pergunta": "Qual é o feminino de 'menino'?", "opcoes": ["Menina", "Menino", "Menine", "Menin"], "resposta": 0},
            {"pergunta": "Qual destas palavras é um adjetivo?", "opcoes": ["Grande", "Casa", "Livro", "Mesa"], "resposta": 0},
            {"pergunta": "Qual é o verbo da frase 'Eu corro todos os dias'?", "opcoes": ["Eu", "Corro", "Todos", "Dias"], "resposta": 1},
            {"pergunta": "Qual destas palavras é um pronome?", "opcoes": ["Ele", "Bonito", "Mesa", "Correr"], "resposta": 0},
            {"pergunta": "Qual é o diminutivo de 'cão'?", "opcoes": ["Cãozinho", "Cãos", "Cãezinho", "Cãinho"], "resposta": 0},
            {"pergunta": "Qual é o plural de 'flor'?", "opcoes": ["Flores", "Flor", "Flors", "Florzinhas"], "resposta": 0},
            {"pergunta": "Qual destas palavras é um advérbio?", "opcoes": ["Rápido", "Correr", "Mesa", "Sempre"], "resposta": 3},
        ],
        "Ciências": [
            {"pergunta": "Qual destes animais é um mamífero?", "opcoes": ["Cobra", "Sapo", "Gato", "Galinha"], "resposta": 2},
            {"pergunta": "Qual parte da planta absorve água?", "opcoes": ["Folha", "Caule", "Raiz", "Flor"], "resposta": 2},
            {"pergunta": "Qual destes é um inseto?", "opcoes": ["Peixe", "Sapo", "Borboleta", "Cachorro"], "resposta": 2},
            {"pergunta": "O que a vaca nos dá?", "opcoes": ["Leite", "Ovos", "Carne", "Lã"], "resposta": 0},
            {"pergunta": "Qual desses é um animal doméstico?", "opcoes": ["Leão", "Tigre", "Gato", "Elefante"], "resposta": 2},
            {"pergunta": "Qual é o estado da água em temperatura ambiente?", "opcoes": ["Sólido", "Líquido", "Gasoso", "Plasma"], "resposta": 1},
            {"pergunta": "Qual é o órgão responsável pela respiração?", "opcoes": ["Coração", "Pulmão", "Fígado", "Estômago"], "resposta": 1},
            {"pergunta": "Qual destes é um corpo celeste?", "opcoes": ["Árvore", "Montanha", "Sol", "Rio"], "resposta": 2},
            {"pergunta": "O que é fotossíntese?", "opcoes": ["Processo de digestão", "Processo de respiração", "Processo de produção de alimento nas plantas", "Processo de circulação sanguínea"], "resposta": 2},
            {"pergunta": "Qual é o maior planeta do sistema solar?", "opcoes": ["Terra", "Marte", "Júpiter", "Saturno"], "resposta": 2},
        ],
        "História": [
            {"pergunta": "Quem descobriu o Brasil?", "opcoes": ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], "resposta": 1},
            {"pergunta": "O que eram as capitanias hereditárias?", "opcoes": ["Divisões administrativas no Brasil Colônia", "Tipos de plantações", "Grupos de indígenas", "Territórios na África"], "resposta": 0},
            {"pergunta": "Quem proclamou a independência do Brasil?", "opcoes": ["Dom Pedro I", "Dom Pedro II", "Tiradentes", "Deodoro da Fonseca"], "resposta": 0},
            {"pergunta": "Quem foi Tiradentes?", "opcoes": ["Um pintor", "Um médico", "Um dentista e herói da Inconfidência Mineira", "Um presidente"], "resposta": 2},
            {"pergunta": "O que é uma aldeia indígena?", "opcoes": ["Um grupo de animais", "Um grupo de casas onde vivem indígenas", "Uma cidade grande", "Um tipo de planta"], "resposta": 1},
            {"pergunta": "O que é uma bandeira?", "opcoes": ["Um símbolo de um país", "Uma planta", "Um animal", "Uma montanha"], "resposta": 0},
            {"pergunta": "O que é um museu?", "opcoes": ["Um lugar onde se guardam objetos históricos", "Uma escola", "Um hospital", "Um parque"], "resposta": 0},
            {"pergunta": "Quem foi Zumbi dos Palmares?", "opcoes": ["Um líder indígena", "Um líder dos escravos", "Um presidente", "Um artista"], "resposta": 1},
            {"pergunta": "Quem foi o primeiro presidente do Brasil?", "opcoes": ["Getúlio Vargas", "Juscelino Kubitschek", "Deodoro da Fonseca", "Dom Pedro II"], "resposta": 2},
            {"pergunta": "Em que ano o Brasil foi descoberto?", "opcoes": ["1492", "1500", "1600", "1700"], "resposta": 1},
        ],
        "Geografia": [
            {"pergunta": "Qual é o maior país da América do Sul?", "opcoes": ["Argentina", "Brasil", "Chile", "Peru"], "resposta": 1},
            {"pergunta": "Qual desses é um rio brasileiro?", "opcoes": ["Nilo", "Amazonas", "Mississipi", "Danúbio"], "resposta": 1},
            {"pergunta": "Qual é a capital do Brasil?", "opcoes": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "resposta": 2},
            {"pergunta": "Qual é o maior país do mundo?", "opcoes": ["Estados Unidos", "China", "Rússia", "Canadá"], "resposta": 2},
            {"pergunta": "Qual continente está localizado o Brasil?", "opcoes": ["América do Sul", "América do Norte", "Europa", "África"], "resposta": 0},
            {"pergunta": "Qual é o nome do maior deserto do mundo?", "opcoes": ["Sahara", "Atacama", "Gobi", "Kalahari"], "resposta": 0},
            {"pergunta": "Qual é o menor continente?", "opcoes": ["África", "Oceania", "Antártica", "Europa"], "resposta": 1},
            {"pergunta": "Qual é o maior continente?", "opcoes": ["África", "América", "Ásia", "Europa"], "resposta": 2},
            {"pergunta": "Qual é o maior oceano?", "opcoes": ["Atlântico", "Pacífico", "Índico", "Ártico"], "resposta": 1},
            {"pergunta": "Qual país tem a maior população?", "opcoes": ["Estados Unidos", "Índia", "Brasil", "China"], "resposta": 3},
        ],
        "Computação": [
            {"pergunta": "O que é um software?", "opcoes": ["Um programa de computador", "Um hardware", "Um periférico", "Um sistema operacional"], "resposta": 0},
            {"pergunta": "Qual desses dispositivos é de entrada?", "opcoes": ["Monitor", "Impressora", "Teclado", "CPU"], "resposta": 2},
            {"pergunta": "Para que serve o mouse?", "opcoes": ["Digitar", "Selecionar itens na tela", "Armazenar dados", "Exibir imagens"], "resposta": 1},
            {"pergunta": "O que é um vírus de computador?", "opcoes": ["Um hardware", "Um software malicioso", "Um sistema operacional", "Um navegador"], "resposta": 1},
            {"pergunta": "Qual dispositivo usamos para digitar?", "opcoes": ["Mouse", "Teclado", "Monitor", "Impressora"], "resposta": 1},
            {"pergunta": "Qual parte do computador mostra as imagens?", "opcoes": ["Mouse", "Teclado", "Monitor", "CPU"], "resposta": 2},
            {"pergunta": "Qual parte do computador armazena informações?", "opcoes": ["Monitor", "Teclado", "Mouse", "HD"], "resposta": 3},
            {"pergunta": "Qual desses é um navegador de internet?", "opcoes": ["Windows", "Word", "Chrome", "Excel"], "resposta": 2},
            {"pergunta": "O que significa a sigla 'CPU'?", "opcoes": ["Central Processing Unit", "Computer Personal Unit", "Central Personal Unit", "Computer Processing Unit"], "resposta": 0},
            {"pergunta": "Qual desses é um sistema operacional?", "opcoes": ["Microsoft Word", "Google Chrome", "Windows", "Excel"], "resposta": 2},
        ],
        "Arte": [
            {"pergunta": "Qual destas é uma cor primária?", "opcoes": ["Verde", "Amarelo", "Roxo", "Laranja"], "resposta": 1},
            {"pergunta": "Qual destes é um material usado para desenhar?", "opcoes": ["Papel", "Lápis", "Tesoura", "Cola"], "resposta": 1},
            {"pergunta": "Qual destes é um artista famoso?", "opcoes": ["Leonardo da Vinci", "Isaac Newton", "Albert Einstein", "Galileu Galilei"], "resposta": 0},
            {"pergunta": "Qual destes é um estilo de dança?", "opcoes": ["Ballet", "Cálculo", "Geometria", "Física"], "resposta": 0},
            {"pergunta": "Qual destes é um instrumento musical?", "opcoes": ["Violino", "Bola", "Livro", "Computador"], "resposta": 0},
            {"pergunta": "O que usamos para pintar?", "opcoes": ["Pincel", "Cola", "Tesoura", "Borracha"], "resposta": 0},
            {"pergunta": "Qual destes é um gênero musical?", "opcoes": ["Rock", "Física", "Matemática", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destas é uma técnica de pintura?", "opcoes": ["Aquarela", "Biologia", "História", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destes é um famoso pintor?", "opcoes": ["Van Gogh", "Einstein", "Newton", "Edison"], "resposta": 0},
            {"pergunta": "Qual destas é uma forma de arte?", "opcoes": ["Escultura", "Cálculo", "Análise", "Pesquisa"], "resposta": 0},
        ]
    },
    "4° Ano": {
        "Matemática": [
            {"pergunta": "Quanto é 12 + 8?", "opcoes": ["20", "21", "22", "23"], "resposta": 0},
            {"pergunta": "Quanto é 15 - 7?", "opcoes": ["7", "8", "9", "10"], "resposta": 1},
            {"pergunta": "Quanto é 7 x 3?", "opcoes": ["20", "21", "22", "23"], "resposta": 1},
            {"pergunta": "Quanto é 24 ÷ 6?", "opcoes": ["3", "4", "5", "6"], "resposta": 1},
            {"pergunta": "Quanto é 10 + 15?", "opcoes": ["24", "25", "26", "27"], "resposta": 1},
            {"pergunta": "Quanto é 30 - 12?", "opcoes": ["17", "18", "19", "20"], "resposta": 1},
            {"pergunta": "Quanto é 5 x 5?", "opcoes": ["20", "25", "30", "35"], "resposta": 1},
            {"pergunta": "Quanto é 40 ÷ 8?", "opcoes": ["4", "5", "6", "7"], "resposta": 0},
            {"pergunta": "Quanto é 18 + 7?", "opcoes": ["24", "25", "26", "27"], "resposta": 1},
            {"pergunta": "Quanto é 25 - 9?", "opcoes": ["15", "16", "17", "18"], "resposta": 2},
        ],
        "Língua Portuguesa": [
            {"pergunta": "Qual é o antônimo de 'feliz'?", "opcoes": ["Triste", "Contente", "Alegre", "Satisfeito"], "resposta": 0},
            {"pergunta": "Qual é o plural de 'flor'?", "opcoes": ["Flores", "Flor", "Flors", "Florzinhas"], "resposta": 0},
            {"pergunta": "Qual destas palavras é um advérbio?", "opcoes": ["Rápido", "Correr", "Mesa", "Sempre"], "resposta": 3},
            {"pergunta": "Qual é o sujeito da frase 'O gato dorme no sofá'?", "opcoes": ["Gato", "Dorme", "No", "Sofá"], "resposta": 0},
            {"pergunta": "Qual é o feminino de 'ator'?", "opcoes": ["Atora", "Atoriza", "Atoriz", "Atriz"], "resposta": 3},
            {"pergunta": "Qual é o verbo da frase 'Ela canta bem'?", "opcoes": ["Ela", "Canta", "Bem", "Cantar"], "resposta": 1},
            {"pergunta": "Qual destas palavras é um substantivo abstrato?", "opcoes": ["Amor", "Mesa", "Cadeira", "Livro"], "resposta": 0},
            {"pergunta": "Qual é a forma diminutiva de 'casa'?", "opcoes": ["Casinha", "Casa", "Casão", "Casoca"], "resposta": 0},
            {"pergunta": "Qual destas palavras é um adjetivo?", "opcoes": ["Alto", "Mesa", "Correr", "Livro"], "resposta": 0},
            {"pergunta": "Qual é o coletivo de 'abelha'?", "opcoes": ["Abelharada", "Abelhal", "Enxame", "Colmeia"], "resposta": 2},
        ],
        "Ciências": [
            {"pergunta": "Qual é o maior planeta do sistema solar?", "opcoes": ["Terra", "Marte", "Júpiter", "Saturno"], "resposta": 2},
            {"pergunta": "Qual parte da planta realiza a fotossíntese?", "opcoes": ["Raiz", "Caule", "Folha", "Flor"], "resposta": 2},
            {"pergunta": "Qual destes animais é um anfíbio?", "opcoes": ["Sapo", "Cachorro", "Gato", "Leão"], "resposta": 0},
            {"pergunta": "Qual destes animais é uma ave?", "opcoes": ["Cachorro", "Gato", "Papagaio", "Leão"], "resposta": 2},
            {"pergunta": "O que é um ecossistema?", "opcoes": ["Um grupo de animais", "Uma comunidade de seres vivos interagindo com o meio ambiente", "Uma árvore", "Um rio"], "resposta": 1},
            {"pergunta": "O que é um herbívoro?", "opcoes": ["Um animal que come carne", "Um animal que come plantas", "Um animal que come tudo", "Um animal que não come"], "resposta": 1},
            {"pergunta": "Qual é a função do coração?", "opcoes": ["Respirar", "Bombear sangue", "Digestão", "Mover o corpo"], "resposta": 1},
            {"pergunta": "Qual destes é um exemplo de cadeia alimentar?", "opcoes": ["Planta -> Herbívoro -> Carnívoro", "Planta -> Carnívoro -> Herbívoro", "Herbívoro -> Planta -> Carnívoro", "Carnívoro -> Herbívoro -> Planta"], "resposta": 0},
            {"pergunta": "Qual é o estado físico da água a 100°C?", "opcoes": ["Sólido", "Líquido", "Gasoso", "Plasma"], "resposta": 2},
            {"pergunta": "Qual é a função do pulmão?", "opcoes": ["Digestão", "Respiração", "Circulação", "Locomoção"], "resposta": 1},
        ],
        "História": [
            {"pergunta": "Quem proclamou a independência do Brasil?", "opcoes": ["Dom Pedro I", "Dom Pedro II", "Tiradentes", "Deodoro da Fonseca"], "resposta": 0},
            {"pergunta": "Quem foi Tiradentes?", "opcoes": ["Um pintor", "Um médico", "Um dentista e herói da Inconfidência Mineira", "Um presidente"], "resposta": 2},
            {"pergunta": "O que é uma aldeia indígena?", "opcoes": ["Um grupo de animais", "Um grupo de casas onde vivem indígenas", "Uma cidade grande", "Um tipo de planta"], "resposta": 1},
            {"pergunta": "O que é uma bandeira?", "opcoes": ["Um símbolo de um país", "Uma planta", "Um animal", "Uma montanha"], "resposta": 0},
            {"pergunta": "O que é um museu?", "opcoes": ["Um lugar onde se guardam objetos históricos", "Uma escola", "Um hospital", "Um parque"], "resposta": 0},
            {"pergunta": "Quem foi Zumbi dos Palmares?", "opcoes": ["Um líder indígena", "Um líder dos escravos", "Um presidente", "Um artista"], "resposta": 1},
            {"pergunta": "Quem foi o primeiro presidente do Brasil?", "opcoes": ["Getúlio Vargas", "Juscelino Kubitschek", "Deodoro da Fonseca", "Dom Pedro II"], "resposta": 2},
            {"pergunta": "Em que ano o Brasil foi descoberto?", "opcoes": ["1492", "1500", "1600", "1700"], "resposta": 1},
            {"pergunta": "Quem descobriu o Brasil?", "opcoes": ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], "resposta": 1},
            {"pergunta": "O que eram as capitanias hereditárias?", "opcoes": ["Divisões administrativas no Brasil Colônia", "Tipos de plantações", "Grupos de indígenas", "Territórios na África"], "resposta": 0},
        ],
        "Geografia": [
            {"pergunta": "Qual é o maior país da América do Sul?", "opcoes": ["Argentina", "Brasil", "Chile", "Peru"], "resposta": 1},
            {"pergunta": "Qual desses é um rio brasileiro?", "opcoes": ["Nilo", "Amazonas", "Mississipi", "Danúbio"], "resposta": 1},
            {"pergunta": "Qual é a capital do Brasil?", "opcoes": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "resposta": 2},
            {"pergunta": "Qual é o maior país do mundo?", "opcoes": ["Estados Unidos", "China", "Rússia", "Canadá"], "resposta": 2},
            {"pergunta": "Qual continente está localizado o Brasil?", "opcoes": ["América do Sul", "América do Norte", "Europa", "África"], "resposta": 0},
            {"pergunta": "Qual é o nome do maior deserto do mundo?", "opcoes": ["Sahara", "Atacama", "Gobi", "Kalahari"], "resposta": 0},
            {"pergunta": "Qual é o menor continente?", "opcoes": ["África", "Oceania", "Antártica", "Europa"], "resposta": 1},
            {"pergunta": "Qual é o maior continente?", "opcoes": ["África", "América", "Ásia", "Europa"], "resposta": 2},
            {"pergunta": "Qual é o maior oceano?", "opcoes": ["Atlântico", "Pacífico", "Índico", "Ártico"], "resposta": 1},
            {"pergunta": "Qual país tem a maior população?", "opcoes": ["Estados Unidos", "Índia", "Brasil", "China"], "resposta": 3},
        ],
        "Computação": [
            {"pergunta": "O que é um software?", "opcoes": ["Um programa de computador", "Um hardware", "Um periférico", "Um sistema operacional"], "resposta": 0},
            {"pergunta": "Qual desses dispositivos é de entrada?", "opcoes": ["Monitor", "Impressora", "Teclado", "CPU"], "resposta": 2},
            {"pergunta": "Para que serve o mouse?", "opcoes": ["Digitar", "Selecionar itens na tela", "Armazenar dados", "Exibir imagens"], "resposta": 1},
            {"pergunta": "O que é um vírus de computador?", "opcoes": ["Um hardware", "Um software malicioso", "Um sistema operacional", "Um navegador"], "resposta": 1},
            {"pergunta": "Qual dispositivo usamos para digitar?", "opcoes": ["Mouse", "Teclado", "Monitor", "Impressora"], "resposta": 1},
            {"pergunta": "Qual parte do computador mostra as imagens?", "opcoes": ["Mouse", "Teclado", "Monitor", "CPU"], "resposta": 2},
            {"pergunta": "Qual parte do computador armazena informações?", "opcoes": ["Monitor", "Teclado", "Mouse", "HD"], "resposta": 3},
            {"pergunta": "Qual desses é um navegador de internet?", "opcoes": ["Windows", "Word", "Chrome", "Excel"], "resposta": 2},
            {"pergunta": "O que significa a sigla 'CPU'?", "opcoes": ["Central Processing Unit", "Computer Personal Unit", "Central Personal Unit", "Computer Processing Unit"], "resposta": 0},
            {"pergunta": "Qual desses é um sistema operacional?", "opcoes": ["Microsoft Word", "Google Chrome", "Windows", "Excel"], "resposta": 2},
        ],
        "Arte": [
            {"pergunta": "Qual destas é uma cor primária?", "opcoes": ["Verde", "Amarelo", "Roxo", "Laranja"], "resposta": 1},
            {"pergunta": "Qual destes é um material usado para desenhar?", "opcoes": ["Papel", "Lápis", "Tesoura", "Cola"], "resposta": 1},
            {"pergunta": "Qual destes é um artista famoso?", "opcoes": ["Leonardo da Vinci", "Isaac Newton", "Albert Einstein", "Galileu Galilei"], "resposta": 0},
            {"pergunta": "Qual destes é um estilo de dança?", "opcoes": ["Ballet", "Cálculo", "Geometria", "Física"], "resposta": 0},
            {"pergunta": "Qual destes é um instrumento musical?", "opcoes": ["Violino", "Bola", "Livro", "Computador"], "resposta": 0},
            {"pergunta": "O que usamos para pintar?", "opcoes": ["Pincel", "Cola", "Tesoura", "Borracha"], "resposta": 0},
            {"pergunta": "Qual destes é um gênero musical?", "opcoes": ["Rock", "Física", "Matemática", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destas é uma técnica de pintura?", "opcoes": ["Aquarela", "Biologia", "História", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destes é um famoso pintor?", "opcoes": ["Van Gogh", "Einstein", "Newton", "Edison"], "resposta": 0},
            {"pergunta": "Qual destas é uma forma de arte?", "opcoes": ["Escultura", "Cálculo", "Análise", "Pesquisa"], "resposta": 0},
        ]
    },
    # Continuar preenchendo para os anos 5° ao 9°
    "5° Ano": {
        "Matemática": [
            {"pergunta": "Quanto é 12 + 8?", "opcoes": ["20", "21", "22", "23"], "resposta": 0},
            {"pergunta": "Quanto é 15 - 7?", "opcoes": ["7", "8", "9", "10"], "resposta": 1},
            {"pergunta": "Quanto é 7 x 3?", "opcoes": ["20", "21", "22", "23"], "resposta": 1},
            {"pergunta": "Quanto é 24 ÷ 6?", "opcoes": ["3", "4", "5", "6"], "resposta": 1},
            {"pergunta": "Quanto é 10 + 15?", "opcoes": ["24", "25", "26", "27"], "resposta": 1},
            {"pergunta": "Quanto é 30 - 12?", "opcoes": ["17", "18", "19", "20"], "resposta": 1},
            {"pergunta": "Quanto é 5 x 5?", "opcoes": ["20", "25", "30", "35"], "resposta": 1},
            {"pergunta": "Quanto é 40 ÷ 8?", "opcoes": ["4", "5", "6", "7"], "resposta": 0},
            {"pergunta": "Quanto é 18 + 7?", "opcoes": ["24", "25", "26", "27"], "resposta": 1},
            {"pergunta": "Quanto é 25 - 9?", "opcoes": ["15", "16", "17", "18"], "resposta": 2},
        ],
        "Língua Portuguesa": [
            {"pergunta": "Qual é o antônimo de 'feliz'?", "opcoes": ["Triste", "Contente", "Alegre", "Satisfeito"], "resposta": 0},
            {"pergunta": "Qual é o plural de 'flor'?", "opcoes": ["Flores", "Flor", "Flors", "Florzinhas"], "resposta": 0},
            {"pergunta": "Qual destas palavras é um advérbio?", "opcoes": ["Rápido", "Correr", "Mesa", "Sempre"], "resposta": 3},
            {"pergunta": "Qual é o sujeito da frase 'O gato dorme no sofá'?", "opcoes": ["Gato", "Dorme", "No", "Sofá"], "resposta": 0},
            {"pergunta": "Qual é o feminino de 'ator'?", "opcoes": ["Atora", "Atoriza", "Atoriz", "Atriz"], "resposta": 3},
            {"pergunta": "Qual é o verbo da frase 'Ela canta bem'?", "opcoes": ["Ela", "Canta", "Bem", "Cantar"], "resposta": 1},
            {"pergunta": "Qual destas palavras é um substantivo abstrato?", "opcoes": ["Amor", "Mesa", "Cadeira", "Livro"], "resposta": 0},
            {"pergunta": "Qual é a forma diminutiva de 'casa'?", "opcoes": ["Casinha", "Casa", "Casão", "Casoca"], "resposta": 0},
            {"pergunta": "Qual destas palavras é um adjetivo?", "opcoes": ["Alto", "Mesa", "Correr", "Livro"], "resposta": 0},
            {"pergunta": "Qual é o coletivo de 'abelha'?", "opcoes": ["Abelharada", "Abelhal", "Enxame", "Colmeia"], "resposta": 2},
        ],
        "Ciências": [
            {"pergunta": "Qual é o maior planeta do sistema solar?", "opcoes": ["Terra", "Marte", "Júpiter", "Saturno"], "resposta": 2},
            {"pergunta": "Qual parte da planta realiza a fotossíntese?", "opcoes": ["Raiz", "Caule", "Folha", "Flor"], "resposta": 2},
            {"pergunta": "Qual destes animais é um anfíbio?", "opcoes": ["Sapo", "Cachorro", "Gato", "Leão"], "resposta": 0},
            {"pergunta": "Qual destes animais é uma ave?", "opcoes": ["Cachorro", "Gato", "Papagaio", "Leão"], "resposta": 2},
            {"pergunta": "O que é um ecossistema?", "opcoes": ["Um grupo de animais", "Uma comunidade de seres vivos interagindo com o meio ambiente", "Uma árvore", "Um rio"], "resposta": 1},
            {"pergunta": "O que é um herbívoro?", "opcoes": ["Um animal que come carne", "Um animal que come plantas", "Um animal que come tudo", "Um animal que não come"], "resposta": 1},
            {"pergunta": "Qual é a função do coração?", "opcoes": ["Respirar", "Bombear sangue", "Digestão", "Mover o corpo"], "resposta": 1},
            {"pergunta": "Qual destes é um exemplo de cadeia alimentar?", "opcoes": ["Planta -> Herbívoro -> Carnívoro", "Planta -> Carnívoro -> Herbívoro", "Herbívoro -> Planta -> Carnívoro", "Carnívoro -> Herbívoro -> Planta"], "resposta": 0},
            {"pergunta": "Qual é o estado físico da água a 100°C?", "opcoes": ["Sólido", "Líquido", "Gasoso", "Plasma"], "resposta": 2},
            {"pergunta": "Qual é a função do pulmão?", "opcoes": ["Digestão", "Respiração", "Circulação", "Locomoção"], "resposta": 1},
        ],
        "História": [
            {"pergunta": "Quem proclamou a independência do Brasil?", "opcoes": ["Dom Pedro I", "Dom Pedro II", "Tiradentes", "Deodoro da Fonseca"], "resposta": 0},
            {"pergunta": "Quem foi Tiradentes?", "opcoes": ["Um pintor", "Um médico", "Um dentista e herói da Inconfidência Mineira", "Um presidente"], "resposta": 2},
            {"pergunta": "O que é uma aldeia indígena?", "opcoes": ["Um grupo de animais", "Um grupo de casas onde vivem indígenas", "Uma cidade grande", "Um tipo de planta"], "resposta": 1},
            {"pergunta": "O que é uma bandeira?", "opcoes": ["Um símbolo de um país", "Uma planta", "Um animal", "Uma montanha"], "resposta": 0},
            {"pergunta": "O que é um museu?", "opcoes": ["Um lugar onde se guardam objetos históricos", "Uma escola", "Um hospital", "Um parque"], "resposta": 0},
            {"pergunta": "Quem foi Zumbi dos Palmares?", "opcoes": ["Um líder indígena", "Um líder dos escravos", "Um presidente", "Um artista"], "resposta": 1},
            {"pergunta": "Quem foi o primeiro presidente do Brasil?", "opcoes": ["Getúlio Vargas", "Juscelino Kubitschek", "Deodoro da Fonseca", "Dom Pedro II"], "resposta": 2},
            {"pergunta": "Em que ano o Brasil foi descoberto?", "opcoes": ["1492", "1500", "1600", "1700"], "resposta": 1},
            {"pergunta": "Quem descobriu o Brasil?", "opcoes": ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], "resposta": 1},
            {"pergunta": "O que eram as capitanias hereditárias?", "opcoes": ["Divisões administrativas no Brasil Colônia", "Tipos de plantações", "Grupos de indígenas", "Territórios na África"], "resposta": 0},
        ],
        "Geografia": [
            {"pergunta": "Qual é o maior país da América do Sul?", "opcoes": ["Argentina", "Brasil", "Chile", "Peru"], "resposta": 1},
            {"pergunta": "Qual desses é um rio brasileiro?", "opcoes": ["Nilo", "Amazonas", "Mississipi", "Danúbio"], "resposta": 1},
            {"pergunta": "Qual é a capital do Brasil?", "opcoes": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "resposta": 2},
            {"pergunta": "Qual é o maior país do mundo?", "opcoes": ["Estados Unidos", "China", "Rússia", "Canadá"], "resposta": 2},
            {"pergunta": "Qual continente está localizado o Brasil?", "opcoes": ["América do Sul", "América do Norte", "Europa", "África"], "resposta": 0},
            {"pergunta": "Qual é o nome do maior deserto do mundo?", "opcoes": ["Sahara", "Atacama", "Gobi", "Kalahari"], "resposta": 0},
            {"pergunta": "Qual é o menor continente?", "opcoes": ["África", "Oceania", "Antártica", "Europa"], "resposta": 1},
            {"pergunta": "Qual é o maior continente?", "opcoes": ["África", "América", "Ásia", "Europa"], "resposta": 2},
            {"pergunta": "Qual é o maior oceano?", "opcoes": ["Atlântico", "Pacífico", "Índico", "Ártico"], "resposta": 1},
            {"pergunta": "Qual país tem a maior população?", "opcoes": ["Estados Unidos", "Índia", "Brasil", "China"], "resposta": 3},
        ],
        "Computação": [
            {"pergunta": "O que é um software?", "opcoes": ["Um programa de computador", "Um hardware", "Um periférico", "Um sistema operacional"], "resposta": 0},
            {"pergunta": "Qual desses dispositivos é de entrada?", "opcoes": ["Monitor", "Impressora", "Teclado", "CPU"], "resposta": 2},
            {"pergunta": "Para que serve o mouse?", "opcoes": ["Digitar", "Selecionar itens na tela", "Armazenar dados", "Exibir imagens"], "resposta": 1},
            {"pergunta": "O que é um vírus de computador?", "opcoes": ["Um hardware", "Um software malicioso", "Um sistema operacional", "Um navegador"], "resposta": 1},
            {"pergunta": "Qual dispositivo usamos para digitar?", "opcoes": ["Mouse", "Teclado", "Monitor", "Impressora"], "resposta": 1},
            {"pergunta": "Qual parte do computador mostra as imagens?", "opcoes": ["Mouse", "Teclado", "Monitor", "CPU"], "resposta": 2},
            {"pergunta": "Qual parte do computador armazena informações?", "opcoes": ["Monitor", "Teclado", "Mouse", "HD"], "resposta": 3},
            {"pergunta": "Qual desses é um navegador de internet?", "opcoes": ["Windows", "Word", "Chrome", "Excel"], "resposta": 2},
            {"pergunta": "O que significa a sigla 'CPU'?", "opcoes": ["Central Processing Unit", "Computer Personal Unit", "Central Personal Unit", "Computer Processing Unit"], "resposta": 0},
            {"pergunta": "Qual desses é um sistema operacional?", "opcoes": ["Microsoft Word", "Google Chrome", "Windows", "Excel"], "resposta": 2},
        ],
        "Arte": [
            {"pergunta": "Qual destas é uma cor primária?", "opcoes": ["Verde", "Amarelo", "Roxo", "Laranja"], "resposta": 1},
            {"pergunta": "Qual destes é um material usado para desenhar?", "opcoes": ["Papel", "Lápis", "Tesoura", "Cola"], "resposta": 1},
            {"pergunta": "Qual destes é um artista famoso?", "opcoes": ["Leonardo da Vinci", "Isaac Newton", "Albert Einstein", "Galileu Galilei"], "resposta": 0},
            {"pergunta": "Qual destes é um estilo de dança?", "opcoes": ["Ballet", "Cálculo", "Geometria", "Física"], "resposta": 0},
            {"pergunta": "Qual destes é um instrumento musical?", "opcoes": ["Violino", "Bola", "Livro", "Computador"], "resposta": 0},
            {"pergunta": "O que usamos para pintar?", "opcoes": ["Pincel", "Cola", "Tesoura", "Borracha"], "resposta": 0},
            {"pergunta": "Qual destes é um gênero musical?", "opcoes": ["Rock", "Física", "Matemática", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destas é uma técnica de pintura?", "opcoes": ["Aquarela", "Biologia", "História", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destes é um famoso pintor?", "opcoes": ["Van Gogh", "Einstein", "Newton", "Edison"], "resposta": 0},
            {"pergunta": "Qual destas é uma forma de arte?", "opcoes": ["Escultura", "Cálculo", "Análise", "Pesquisa"], "resposta": 0},
        ]
    },
    "6° Ano": {
        "Matemática": [
            {"pergunta": "Quanto é 45 + 32?", "opcoes": ["76", "77", "78", "79"], "resposta": 2},
            {"pergunta": "Quanto é 56 - 18?", "opcoes": ["38", "39", "40", "41"], "resposta": 0},
            {"pergunta": "Quanto é 9 x 7?", "opcoes": ["62", "63", "64", "65"], "resposta": 1},
            {"pergunta": "Quanto é 81 ÷ 9?", "opcoes": ["8", "9", "10", "11"], "resposta": 1},
            {"pergunta": "Quanto é 14 x 5?", "opcoes": ["65", "66", "67", "70"], "resposta": 3},
            {"pergunta": "Quanto é 100 - 44?", "opcoes": ["55", "56", "57", "58"], "resposta": 1},
            {"pergunta": "Quanto é 36 + 28?", "opcoes": ["63", "64", "65", "66"], "resposta": 1},
            {"pergunta": "Quanto é 81 ÷ 3?", "opcoes": ["26", "27", "28", "29"], "resposta": 1},
            {"pergunta": "Quanto é 11 x 8?", "opcoes": ["87", "88", "89", "90"], "resposta": 1},
            {"pergunta": "Quanto é 64 ÷ 8?", "opcoes": ["7", "8", "9", "10"], "resposta": 1},
        ],
        "Língua Portuguesa": [
            {"pergunta": "Qual é o sinônimo de 'alegria'?", "opcoes": ["Tristeza", "Felicidade", "Raiva", "Medo"], "resposta": 1},
            {"pergunta": "Qual é o antônimo de 'rápido'?", "opcoes": ["Veloz", "Ágil", "Devagar", "Furioso"], "resposta": 2},
            {"pergunta": "Qual é o coletivo de 'peixe'?", "opcoes": ["Cardume", "Rebanho", "Bando", "Alcateia"], "resposta": 0},
            {"pergunta": "Qual é o diminutivo de 'casa'?", "opcoes": ["Casinha", "Casa", "Casão", "Casinhas"], "resposta": 0},
            {"pergunta": "Qual é o feminino de 'leão'?", "opcoes": ["Leoa", "Leona", "Leonina", "Leonita"], "resposta": 0},
            {"pergunta": "Qual é a forma correta do verbo 'cantar' no futuro do presente?", "opcoes": ["Cantarei", "Cantava", "Cantou", "Cantado"], "resposta": 0},
            {"pergunta": "Qual é o tempo verbal da frase 'Ele está cantando'?", "opcoes": ["Presente", "Pretérito", "Futuro", "Gerúndio"], "resposta": 3},
            {"pergunta": "Qual é a forma correta de conjugação do verbo 'ver' na primeira pessoa do singular no presente?", "opcoes": ["Vê", "Vejo", "Vemos", "Vês"], "resposta": 1},
            {"pergunta": "Qual é a forma correta do plural de 'cão'?", "opcoes": ["Cãos", "Cãezes", "Cães", "Cãozes"], "resposta": 2},
            {"pergunta": "Qual é o verbo da frase 'Nós estudamos matemática'?", "opcoes": ["Nós", "Estudamos", "Matemática", "Nenhuma das opções"], "resposta": 1},
        ],
        "Ciências": [
            {"pergunta": "Qual é a principal fonte de energia para a Terra?", "opcoes": ["Vento", "Água", "Sol", "Petróleo"], "resposta": 2},
            {"pergunta": "Qual é o gás essencial para a respiração humana?", "opcoes": ["Hidrogênio", "Oxigênio", "Nitrogênio", "Dióxido de carbono"], "resposta": 1},
            {"pergunta": "Qual é o maior órgão do corpo humano?", "opcoes": ["Coração", "Fígado", "Pele", "Pulmão"], "resposta": 2},
            {"pergunta": "Qual é a unidade básica da vida?", "opcoes": ["Célula", "Átomo", "Molécula", "Órgão"], "resposta": 0},
            {"pergunta": "Qual é o processo pelo qual as plantas produzem alimento?", "opcoes": ["Fotossíntese", "Respiração", "Digestão", "Transpiração"], "resposta": 0},
            {"pergunta": "Qual destes é um metal?", "opcoes": ["Ouro", "Plástico", "Vidro", "Papel"], "resposta": 0},
            {"pergunta": "Qual é o estado físico da água a 0°C?", "opcoes": ["Líquido", "Sólido", "Gasoso", "Plasma"], "resposta": 1},
            {"pergunta": "Qual é o maior planeta do sistema solar?", "opcoes": ["Terra", "Marte", "Júpiter", "Saturno"], "resposta": 2},
            {"pergunta": "Qual é a função dos pulmões?", "opcoes": ["Bombear sangue", "Filtrar sangue", "Respirar", "Digestionar"], "resposta": 2},
            {"pergunta": "Qual é a parte do corpo humano responsável pelo pensamento?", "opcoes": ["Coração", "Cérebro", "Fígado", "Estômago"], "resposta": 1},
        ],
        "História": [
            {"pergunta": "Quem foi o primeiro presidente do Brasil?", "opcoes": ["Getúlio Vargas", "Juscelino Kubitschek", "Deodoro da Fonseca", "Dom Pedro II"], "resposta": 2},
            {"pergunta": "Quem proclamou a independência do Brasil?", "opcoes": ["Dom Pedro I", "Dom Pedro II", "Tiradentes", "Deodoro da Fonseca"], "resposta": 0},
            {"pergunta": "Quem descobriu o Brasil?", "opcoes": ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], "resposta": 1},
            {"pergunta": "O que foram as capitanias hereditárias?", "opcoes": ["Divisões administrativas no Brasil Colônia", "Tipos de plantações", "Grupos de indígenas", "Territórios na África"], "resposta": 0},
            {"pergunta": "Quem foi Tiradentes?", "opcoes": ["Um pintor", "Um médico", "Um dentista e herói da Inconfidência Mineira", "Um presidente"], "resposta": 2},
            {"pergunta": "Quem foi Zumbi dos Palmares?", "opcoes": ["Um líder indígena", "Um líder dos escravos", "Um presidente", "Um artista"], "resposta": 1},
            {"pergunta": "O que é uma aldeia indígena?", "opcoes": ["Um grupo de animais", "Um grupo de casas onde vivem indígenas", "Uma cidade grande", "Um tipo de planta"], "resposta": 1},
            {"pergunta": "O que é um museu?", "opcoes": ["Um lugar onde se guardam objetos históricos", "Uma escola", "Um hospital", "Um parque"], "resposta": 0},
            {"pergunta": "Quem foi o líder da Revolução Francesa?", "opcoes": ["Napoleão Bonaparte", "Louis XVI", "Robespierre", "Voltaire"], "resposta": 2},
            {"pergunta": "Quem foi o imperador romano conhecido por sua crueldade?", "opcoes": ["César", "Augusto", "Nero", "Trajano"], "resposta": 2},
        ],
        "Geografia": [
            {"pergunta": "Qual é o maior país da América do Sul?", "opcoes": ["Argentina", "Brasil", "Chile", "Peru"], "resposta": 1},
            {"pergunta": "Qual é o rio mais longo do mundo?", "opcoes": ["Nilo", "Amazonas", "Mississipi", "Yangtze"], "resposta": 0},
            {"pergunta": "Qual é a capital do Brasil?", "opcoes": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "resposta": 2},
            {"pergunta": "Qual é o maior continente?", "opcoes": ["África", "América", "Ásia", "Europa"], "resposta": 2},
            {"pergunta": "Qual é o menor continente?", "opcoes": ["África", "Oceania", "Antártica", "Europa"], "resposta": 1},
            {"pergunta": "Qual é o maior oceano?", "opcoes": ["Atlântico", "Pacífico", "Índico", "Ártico"], "resposta": 1},
            {"pergunta": "Qual é a maior floresta tropical do mundo?", "opcoes": ["Floresta Amazônica", "Floresta Negra", "Floresta de Sherwood", "Floresta de Borneo"], "resposta": 0},
            {"pergunta": "Qual país tem a maior população do mundo?", "opcoes": ["Índia", "Estados Unidos", "China", "Brasil"], "resposta": 2},
            {"pergunta": "Qual é a maior montanha do mundo?", "opcoes": ["Monte Everest", "K2", "Kangchenjunga", "Lhotse"], "resposta": 0},
            {"pergunta": "Qual é a capital da França?", "opcoes": ["Londres", "Paris", "Berlim", "Roma"], "resposta": 1},
        ],
        "Computação": [
            {"pergunta": "O que é um software?", "opcoes": ["Um programa de computador", "Um hardware", "Um periférico", "Um sistema operacional"], "resposta": 0},
            {"pergunta": "Qual desses dispositivos é de entrada?", "opcoes": ["Monitor", "Impressora", "Teclado", "CPU"], "resposta": 2},
            {"pergunta": "Para que serve o mouse?", "opcoes": ["Digitar", "Selecionar itens na tela", "Armazenar dados", "Exibir imagens"], "resposta": 1},
            {"pergunta": "O que é um vírus de computador?", "opcoes": ["Um hardware", "Um software malicioso", "Um sistema operacional", "Um navegador"], "resposta": 1},
            {"pergunta": "Qual dispositivo usamos para digitar?", "opcoes": ["Mouse", "Teclado", "Monitor", "Impressora"], "resposta": 1},
            {"pergunta": "Qual parte do computador mostra as imagens?", "opcoes": ["Mouse", "Teclado", "Monitor", "CPU"], "resposta": 2},
            {"pergunta": "Qual parte do computador armazena informações?", "opcoes": ["Monitor", "Teclado", "Mouse", "HD"], "resposta": 3},
            {"pergunta": "Qual desses é um navegador de internet?", "opcoes": ["Windows", "Word", "Chrome", "Excel"], "resposta": 2},
            {"pergunta": "O que significa a sigla 'CPU'?", "opcoes": ["Central Processing Unit", "Computer Personal Unit", "Central Personal Unit", "Computer Processing Unit"], "resposta": 0},
            {"pergunta": "Qual desses é um sistema operacional?", "opcoes": ["Microsoft Word", "Google Chrome", "Windows", "Excel"], "resposta": 2},
        ],
        "Arte": [
            {"pergunta": "Qual destas é uma cor primária?", "opcoes": ["Verde", "Amarelo", "Roxo", "Laranja"], "resposta": 1},
            {"pergunta": "Qual destes é um material usado para desenhar?", "opcoes": ["Papel", "Lápis", "Tesoura", "Cola"], "resposta": 1},
            {"pergunta": "Qual destes é um artista famoso?", "opcoes": ["Leonardo da Vinci", "Isaac Newton", "Albert Einstein", "Galileu Galilei"], "resposta": 0},
            {"pergunta": "Qual destes é um estilo de dança?", "opcoes": ["Ballet", "Cálculo", "Geometria", "Física"], "resposta": 0},
            {"pergunta": "Qual destes é um instrumento musical?", "opcoes": ["Violino", "Bola", "Livro", "Computador"], "resposta": 0},
            {"pergunta": "O que usamos para pintar?", "opcoes": ["Pincel", "Cola", "Tesoura", "Borracha"], "resposta": 0},
            {"pergunta": "Qual destes é um gênero musical?", "opcoes": ["Rock", "Física", "Matemática", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destas é uma técnica de pintura?", "opcoes": ["Aquarela", "Biologia", "História", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destes é um famoso pintor?", "opcoes": ["Van Gogh", "Einstein", "Newton", "Edison"], "resposta": 0},
            {"pergunta": "Qual destas é uma forma de arte?", "opcoes": ["Escultura", "Cálculo", "Análise", "Pesquisa"], "resposta": 0},
        ]
    },
    "7° Ano": {
        "Matemática": [
            {"pergunta": "Quanto é 123 + 456?", "opcoes": ["579", "589", "599", "609"], "resposta": 0},
            {"pergunta": "Quanto é 789 - 321?", "opcoes": ["468", "478", "488", "498"], "resposta": 1},
            {"pergunta": "Quanto é 12 x 12?", "opcoes": ["144", "154", "164", "174"], "resposta": 0},
            {"pergunta": "Quanto é 144 ÷ 12?", "opcoes": ["10", "11", "12", "13"], "resposta": 2},
            {"pergunta": "Qual é a raiz quadrada de 81?", "opcoes": ["7", "8", "9", "10"], "resposta": 2},
            {"pergunta": "Quanto é 11²?", "opcoes": ["120", "121", "122", "123"], "resposta": 1},
            {"pergunta": "Qual é a área de um quadrado de lado 5?", "opcoes": ["20", "25", "30", "35"], "resposta": 1},
            {"pergunta": "Quanto é 15 x 3?", "opcoes": ["45", "50", "55", "60"], "resposta": 0},
            {"pergunta": "Quanto é 60 ÷ 5?", "opcoes": ["10", "11", "12", "13"], "resposta": 2},
            {"pergunta": "Qual é o perímetro de um triângulo de lados 3, 4 e 5?", "opcoes": ["10", "11", "12", "13"], "resposta": 2},
        ],
        "Língua Portuguesa": [
            {"pergunta": "Qual é o sinônimo de 'inteligente'?", "opcoes": ["Burro", "Esperto", "Rápido", "Lento"], "resposta": 1},
            {"pergunta": "Qual é o antônimo de 'alegria'?", "opcoes": ["Felicidade", "Tristeza", "Raiva", "Amor"], "resposta": 1},
            {"pergunta": "Qual é o coletivo de 'livro'?", "opcoes": ["Biblioteca", "Livraria", "Estante", "Livros"], "resposta": 0},
            {"pergunta": "Qual é o diminutivo de 'flor'?", "opcoes": ["Florinha", "Florzinhas", "Florzinha", "Florões"], "resposta": 2},
            {"pergunta": "Qual é o feminino de 'ator'?", "opcoes": ["Atora", "Atriz", "Atoresa", "Atoriza"], "resposta": 1},
            {"pergunta": "Qual é a forma correta do verbo 'correr' no pretérito perfeito?", "opcoes": ["Correu", "Corri", "Corria", "Corrido"], "resposta": 0},
            {"pergunta": "Qual é o tempo verbal da frase 'Nós estudamos ontem'?", "opcoes": ["Presente", "Pretérito", "Futuro", "Gerúndio"], "resposta": 1},
            {"pergunta": "Qual é a forma correta de conjugação do verbo 'estar' na primeira pessoa do singular no presente?", "opcoes": ["Está", "Estás", "Estou", "Estava"], "resposta": 2},
            {"pergunta": "Qual é a forma correta do plural de 'pão'?", "opcoes": ["Pães", "Pãos", "Pãozes", "Pãozões"], "resposta": 0},
            {"pergunta": "Qual é o verbo da frase 'Eles correram para o parque'?", "opcoes": ["Eles", "Correram", "Para", "Parque"], "resposta": 1},
        ],
        "Ciências": [
            {"pergunta": "Qual é o principal componente da água?", "opcoes": ["Hidrogênio", "Oxigênio", "Nitrogênio", "Carbono"], "resposta": 0},
            {"pergunta": "Qual é a função do coração?", "opcoes": ["Respirar", "Bombear sangue", "Digestão", "Mastigação"], "resposta": 1},
            {"pergunta": "Qual é o processo de conversão de água em vapor?", "opcoes": ["Condensação", "Evaporação", "Sublimação", "Solidificação"], "resposta": 1},
            {"pergunta": "Qual destes é um exemplo de fonte de energia renovável?", "opcoes": ["Carvão", "Petróleo", "Vento", "Gás natural"], "resposta": 2},
            {"pergunta": "Qual é o planeta mais próximo do Sol?", "opcoes": ["Marte", "Terra", "Vênus", "Mercúrio"], "resposta": 3},
            {"pergunta": "Qual é o maior animal terrestre?", "opcoes": ["Elefante", "Girafa", "Rinoceronte", "Hipopótamo"], "resposta": 0},
            {"pergunta": "Qual é o processo pelo qual as plantas produzem oxigênio?", "opcoes": ["Fotossíntese", "Respiração", "Transpiração", "Digestão"], "resposta": 0},
            {"pergunta": "Qual é o estado físico da água a 0°C?", "opcoes": ["Líquido", "Sólido", "Gasoso", "Plasma"], "resposta": 1},
            {"pergunta": "Qual é a principal função dos rins?", "opcoes": ["Bombear sangue", "Filtrar sangue", "Respiração", "Digestão"], "resposta": 1},
            {"pergunta": "Qual é a unidade básica da vida?", "opcoes": ["Célula", "Átomo", "Molécula", "Organismo"], "resposta": 0},
        ],
        "História": [
            {"pergunta": "Quem foi o primeiro presidente do Brasil?", "opcoes": ["Getúlio Vargas", "Juscelino Kubitschek", "Deodoro da Fonseca", "Dom Pedro II"], "resposta": 2},
            {"pergunta": "Quem proclamou a independência do Brasil?", "opcoes": ["Dom Pedro I", "Dom Pedro II", "Tiradentes", "Deodoro da Fonseca"], "resposta": 0},
            {"pergunta": "Quem descobriu o Brasil?", "opcoes": ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], "resposta": 1},
            {"pergunta": "O que foram as capitanias hereditárias?", "opcoes": ["Divisões administrativas no Brasil Colônia", "Tipos de plantações", "Grupos de indígenas", "Territórios na África"], "resposta": 0},
            {"pergunta": "Quem foi Tiradentes?", "opcoes": ["Um pintor", "Um médico", "Um dentista e herói da Inconfidência Mineira", "Um presidente"], "resposta": 2},
            {"pergunta": "Quem foi Zumbi dos Palmares?", "opcoes": ["Um líder indígena", "Um líder dos escravos", "Um presidente", "Um artista"], "resposta": 1},
            {"pergunta": "O que é uma aldeia indígena?", "opcoes": ["Um grupo de animais", "Um grupo de casas onde vivem indígenas", "Uma cidade grande", "Um tipo de planta"], "resposta": 1},
            {"pergunta": "O que é um museu?", "opcoes": ["Um lugar onde se guardam objetos históricos", "Uma escola", "Um hospital", "Um parque"], "resposta": 0},
            {"pergunta": "Quem foi o líder da Revolução Francesa?", "opcoes": ["Napoleão Bonaparte", "Louis XVI", "Robespierre", "Voltaire"], "resposta": 2},
            {"pergunta": "Quem foi o imperador romano conhecido por sua crueldade?", "opcoes": ["César", "Augusto", "Nero", "Trajano"], "resposta": 2},
        ],
        "Geografia": [
            {"pergunta": "Qual é o maior país da América do Sul?", "opcoes": ["Argentina", "Brasil", "Chile", "Peru"], "resposta": 1},
            {"pergunta": "Qual é o rio mais longo do mundo?", "opcoes": ["Nilo", "Amazonas", "Mississipi", "Yangtze"], "resposta": 0},
            {"pergunta": "Qual é a capital do Brasil?", "opcoes": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "resposta": 2},
            {"pergunta": "Qual é o maior continente?", "opcoes": ["África", "América", "Ásia", "Europa"], "resposta": 2},
            {"pergunta": "Qual é o menor continente?", "opcoes": ["África", "Oceania", "Antártica", "Europa"], "resposta": 1},
            {"pergunta": "Qual é o maior oceano?", "opcoes": ["Atlântico", "Pacífico", "Índico", "Ártico"], "resposta": 1},
            {"pergunta": "Qual é a maior floresta tropical do mundo?", "opcoes": ["Floresta Amazônica", "Floresta Negra", "Floresta de Sherwood", "Floresta de Borneo"], "resposta": 0},
            {"pergunta": "Qual país tem a maior população do mundo?", "opcoes": ["Índia", "Estados Unidos", "China", "Brasil"], "resposta": 2},
            {"pergunta": "Qual é a maior montanha do mundo?", "opcoes": ["Monte Everest", "K2", "Kangchenjunga", "Lhotse"], "resposta": 0},
            {"pergunta": "Qual é a capital da França?", "opcoes": ["Londres", "Paris", "Berlim", "Roma"], "resposta": 1},
        ],
        "Computação": [
            {"pergunta": "O que é um software?", "opcoes": ["Um programa de computador", "Um hardware", "Um periférico", "Um sistema operacional"], "resposta": 0},
            {"pergunta": "Qual desses dispositivos é de entrada?", "opcoes": ["Monitor", "Impressora", "Teclado", "CPU"], "resposta": 2},
            {"pergunta": "Para que serve o mouse?", "opcoes": ["Digitar", "Selecionar itens na tela", "Armazenar dados", "Exibir imagens"], "resposta": 1},
            {"pergunta": "O que é um vírus de computador?", "opcoes": ["Um hardware", "Um software malicioso", "Um sistema operacional", "Um navegador"], "resposta": 1},
            {"pergunta": "Qual dispositivo usamos para digitar?", "opcoes": ["Mouse", "Teclado", "Monitor", "Impressora"], "resposta": 1},
            {"pergunta": "Qual parte do computador mostra as imagens?", "opcoes": ["Mouse", "Teclado", "Monitor", "CPU"], "resposta": 2},
            {"pergunta": "Qual parte do computador armazena informações?", "opcoes": ["Monitor", "Teclado", "Mouse", "HD"], "resposta": 3},
            {"pergunta": "Qual desses é um navegador de internet?", "opcoes": ["Windows", "Word", "Chrome", "Excel"], "resposta": 2},
            {"pergunta": "O que significa a sigla 'CPU'?", "opcoes": ["Central Processing Unit", "Computer Personal Unit", "Central Personal Unit", "Computer Processing Unit"], "resposta": 0},
            {"pergunta": "Qual desses é um sistema operacional?", "opcoes": ["Microsoft Word", "Google Chrome", "Windows", "Excel"], "resposta": 2},
        ],
        "Arte": [
            {"pergunta": "Qual destas é uma cor primária?", "opcoes": ["Verde", "Amarelo", "Roxo", "Laranja"], "resposta": 1},
            {"pergunta": "Qual destes é um material usado para desenhar?", "opcoes": ["Papel", "Lápis", "Tesoura", "Cola"], "resposta": 1},
            {"pergunta": "Qual destes é um artista famoso?", "opcoes": ["Leonardo da Vinci", "Isaac Newton", "Albert Einstein", "Galileu Galilei"], "resposta": 0},
            {"pergunta": "Qual destes é um estilo de dança?", "opcoes": ["Ballet", "Cálculo", "Geometria", "Física"], "resposta": 0},
            {"pergunta": "Qual destes é um instrumento musical?", "opcoes": ["Violino", "Bola", "Livro", "Computador"], "resposta": 0},
            {"pergunta": "O que usamos para pintar?", "opcoes": ["Pincel", "Cola", "Tesoura", "Borracha"], "resposta": 0},
            {"pergunta": "Qual destes é um gênero musical?", "opcoes": ["Rock", "Física", "Matemática", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destas é uma técnica de pintura?", "opcoes": ["Aquarela", "Biologia", "História", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destes é um famoso pintor?", "opcoes": ["Van Gogh", "Einstein", "Newton", "Edison"], "resposta": 0},
            {"pergunta": "Qual destas é uma forma de arte?", "opcoes": ["Escultura", "Cálculo", "Análise", "Pesquisa"], "resposta": 0},
        ]
    },
    "8° Ano": {
        "Matemática": [
            {"pergunta": "Quanto é 245 + 367?", "opcoes": ["602", "612", "622", "632"], "resposta": 2},
            {"pergunta": "Quanto é 543 - 278?", "opcoes": ["264", "265", "266", "267"], "resposta": 3},
            {"pergunta": "Quanto é 23 x 12?", "opcoes": ["276", "277", "278", "279"], "resposta": 0},
            {"pergunta": "Quanto é 256 ÷ 8?", "opcoes": ["31", "32", "33", "34"], "resposta": 1},
            {"pergunta": "Qual é a raiz quadrada de 121?", "opcoes": ["10", "11", "12", "13"], "resposta": 1},
            {"pergunta": "Quanto é 13²?", "opcoes": ["168", "169", "170", "171"], "resposta": 1},
            {"pergunta": "Qual é a área de um triângulo de base 6 e altura 8?", "opcoes": ["24", "25", "26", "27"], "resposta": 0},
            {"pergunta": "Quanto é 48 x 3?", "opcoes": ["140", "141", "142", "144"], "resposta": 3},
            {"pergunta": "Quanto é 144 ÷ 6?", "opcoes": ["22", "23", "24", "25"], "resposta": 2},
            {"pergunta": "Qual é o perímetro de um quadrado de lado 7?", "opcoes": ["27", "28", "29", "30"], "resposta": 1},
        ],
        "Língua Portuguesa": [
            {"pergunta": "Qual é o sinônimo de 'coragem'?", "opcoes": ["Medo", "Valentia", "Covardia", "Preguiça"], "resposta": 1},
            {"pergunta": "Qual é o antônimo de 'verdade'?", "opcoes": ["Mentira", "Fato", "Realidade", "Sinceridade"], "resposta": 0},
            {"pergunta": "Qual é o coletivo de 'lobo'?", "opcoes": ["Manada", "Bando", "Alcateia", "Grupo"], "resposta": 2},
            {"pergunta": "Qual é o diminutivo de 'passarinho'?", "opcoes": ["Passarote", "Passarote", "Passarote", "Passarote"], "resposta": 2},
            {"pergunta": "Qual é o feminino de 'elefante'?", "opcoes": ["Elefoa", "Elefanta", "Elefantona", "Elefoa"], "resposta": 1},
            {"pergunta": "Qual é a forma correta do verbo 'comer' no futuro do pretérito?", "opcoes": ["Comerá", "Comeria", "Comerei", "Comer"], "resposta": 1},
            {"pergunta": "Qual é o tempo verbal da frase 'Eles haviam terminado a tarefa'?", "opcoes": ["Presente", "Pretérito Mais-que-Perfeito", "Pretérito Perfeito", "Futuro"], "resposta": 1},
            {"pergunta": "Qual é a forma correta de conjugação do verbo 'ir' na primeira pessoa do singular no futuro?", "opcoes": ["Irei", "Vou", "Ia", "Irei"], "resposta": 0},
            {"pergunta": "Qual é a forma correta do plural de 'mão'?", "opcoes": ["Mãos", "Mãos", "Mãos", "Mãos"], "resposta": 0},
            {"pergunta": "Qual é o verbo da frase 'Nós cantaremos na festa'?", "opcoes": ["Nós", "Cantaremos", "Na", "Festa"], "resposta": 1},
        ],
        "Ciências": [
            {"pergunta": "Qual é o principal componente do ar?", "opcoes": ["Oxigênio", "Nitrogênio", "Dióxido de carbono", "Hidrogênio"], "resposta": 1},
            {"pergunta": "Qual é a função dos músculos?", "opcoes": ["Respiração", "Movimento", "Digestão", "Circulação"], "resposta": 1},
            {"pergunta": "Qual é o processo de transformação de gás em líquido?", "opcoes": ["Evaporação", "Sublimação", "Condensação", "Solidificação"], "resposta": 2},
            {"pergunta": "Qual destes é um exemplo de fonte de energia não renovável?", "opcoes": ["Solar", "Eólica", "Hidrelétrica", "Petróleo"], "resposta": 3},
            {"pergunta": "Qual é o planeta mais distante do Sol?", "opcoes": ["Netuno", "Urano", "Saturno", "Júpiter"], "resposta": 0},
            {"pergunta": "Qual é o maior animal aquático?", "opcoes": ["Baleia Azul", "Tubarão Branco", "Golfinho", "Polvo"], "resposta": 0},
            {"pergunta": "Qual é o processo pelo qual os seres vivos se multiplicam?", "opcoes": ["Respiração", "Reprodução", "Digestão", "Locomoção"], "resposta": 1},
            {"pergunta": "Qual é o estado físico da água a 100°C?", "opcoes": ["Líquido", "Sólido", "Gasoso", "Plasma"], "resposta": 2},
            {"pergunta": "Qual é a principal função do fígado?", "opcoes": ["Produzir bile", "Respiração", "Bombear sangue", "Filtrar sangue"], "resposta": 0},
            {"pergunta": "Qual é a unidade básica dos seres vivos?", "opcoes": ["Átomo", "Molécula", "Célula", "Órgão"], "resposta": 2},
        ],
        "História": [
            {"pergunta": "Quem foi o primeiro presidente do Brasil?", "opcoes": ["Getúlio Vargas", "Juscelino Kubitschek", "Deodoro da Fonseca", "Dom Pedro II"], "resposta": 2},
            {"pergunta": "Quem proclamou a independência do Brasil?", "opcoes": ["Dom Pedro I", "Dom Pedro II", "Tiradentes", "Deodoro da Fonseca"], "resposta": 0},
            {"pergunta": "Quem descobriu o Brasil?", "opcoes": ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], "resposta": 1},
            {"pergunta": "O que foram as capitanias hereditárias?", "opcoes": ["Divisões administrativas no Brasil Colônia", "Tipos de plantações", "Grupos de indígenas", "Territórios na África"], "resposta": 0},
            {"pergunta": "Quem foi Tiradentes?", "opcoes": ["Um pintor", "Um médico", "Um dentista e herói da Inconfidência Mineira", "Um presidente"], "resposta": 2},
            {"pergunta": "Quem foi Zumbi dos Palmares?", "opcoes": ["Um líder indígena", "Um líder dos escravos", "Um presidente", "Um artista"], "resposta": 1},
            {"pergunta": "O que é uma aldeia indígena?", "opcoes": ["Um grupo de animais", "Um grupo de casas onde vivem indígenas", "Uma cidade grande", "Um tipo de planta"], "resposta": 1},
            {"pergunta": "O que é um museu?", "opcoes": ["Um lugar onde se guardam objetos históricos", "Uma escola", "Um hospital", "Um parque"], "resposta": 0},
            {"pergunta": "Quem foi o líder da Revolução Francesa?", "opcoes": ["Napoleão Bonaparte", "Louis XVI", "Robespierre", "Voltaire"], "resposta": 2},
            {"pergunta": "Quem foi o imperador romano conhecido por sua crueldade?", "opcoes": ["César", "Augusto", "Nero", "Trajano"], "resposta": 2},
        ],
        "Geografia": [
            {"pergunta": "Qual é o maior país da América do Sul?", "opcoes": ["Argentina", "Brasil", "Chile", "Peru"], "resposta": 1},
            {"pergunta": "Qual é o rio mais longo do mundo?", "opcoes": ["Nilo", "Amazonas", "Mississipi", "Yangtze"], "resposta": 0},
            {"pergunta": "Qual é a capital do Brasil?", "opcoes": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "resposta": 2},
            {"pergunta": "Qual é o maior continente?", "opcoes": ["África", "América", "Ásia", "Europa"], "resposta": 2},
            {"pergunta": "Qual é o menor continente?", "opcoes": ["África", "Oceania", "Antártica", "Europa"], "resposta": 1},
            {"pergunta": "Qual é o maior oceano?", "opcoes": ["Atlântico", "Pacífico", "Índico", "Ártico"], "resposta": 1},
            {"pergunta": "Qual é a maior floresta tropical do mundo?", "opcoes": ["Floresta Amazônica", "Floresta Negra", "Floresta de Sherwood", "Floresta de Borneo"], "resposta": 0},
            {"pergunta": "Qual país tem a maior população do mundo?", "opcoes": ["Índia", "Estados Unidos", "China", "Brasil"], "resposta": 2},
            {"pergunta": "Qual é a maior montanha do mundo?", "opcoes": ["Monte Everest", "K2", "Kangchenjunga", "Lhotse"], "resposta": 0},
            {"pergunta": "Qual é a capital da França?", "opcoes": ["Londres", "Paris", "Berlim", "Roma"], "resposta": 1},
        ],
        "Computação": [
            {"pergunta": "O que é um software?", "opcoes": ["Um programa de computador", "Um hardware", "Um periférico", "Um sistema operacional"], "resposta": 0},
            {"pergunta": "Qual desses dispositivos é de entrada?", "opcoes": ["Monitor", "Impressora", "Teclado", "CPU"], "resposta": 2},
            {"pergunta": "Para que serve o mouse?", "opcoes": ["Digitar", "Selecionar itens na tela", "Armazenar dados", "Exibir imagens"], "resposta": 1},
            {"pergunta": "O que é um vírus de computador?", "opcoes": ["Um hardware", "Um software malicioso", "Um sistema operacional", "Um navegador"], "resposta": 1},
            {"pergunta": "Qual dispositivo usamos para digitar?", "opcoes": ["Mouse", "Teclado", "Monitor", "Impressora"], "resposta": 1},
            {"pergunta": "Qual parte do computador mostra as imagens?", "opcoes": ["Mouse", "Teclado", "Monitor", "CPU"], "resposta": 2},
            {"pergunta": "Qual parte do computador armazena informações?", "opcoes": ["Monitor", "Teclado", "Mouse", "HD"], "resposta": 3},
            {"pergunta": "Qual desses é um navegador de internet?", "opcoes": ["Windows", "Word", "Chrome", "Excel"], "resposta": 2},
            {"pergunta": "O que significa a sigla 'CPU'?", "opcoes": ["Central Processing Unit", "Computer Personal Unit", "Central Personal Unit", "Computer Processing Unit"], "resposta": 0},
            {"pergunta": "Qual desses é um sistema operacional?", "opcoes": ["Microsoft Word", "Google Chrome", "Windows", "Excel"], "resposta": 2},
        ],
        "Arte": [
            {"pergunta": "Qual destas é uma cor primária?", "opcoes": ["Verde", "Amarelo", "Roxo", "Laranja"], "resposta": 1},
            {"pergunta": "Qual destes é um material usado para desenhar?", "opcoes": ["Papel", "Lápis", "Tesoura", "Cola"], "resposta": 1},
            {"pergunta": "Qual destes é um artista famoso?", "opcoes": ["Leonardo da Vinci", "Isaac Newton", "Albert Einstein", "Galileu Galilei"], "resposta": 0},
            {"pergunta": "Qual destes é um estilo de dança?", "opcoes": ["Ballet", "Cálculo", "Geometria", "Física"], "resposta": 0},
            {"pergunta": "Qual destes é um instrumento musical?", "opcoes": ["Violino", "Bola", "Livro", "Computador"], "resposta": 0},
            {"pergunta": "O que usamos para pintar?", "opcoes": ["Pincel", "Cola", "Tesoura", "Borracha"], "resposta": 0},
            {"pergunta": "Qual destes é um gênero musical?", "opcoes": ["Rock", "Física", "Matemática", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destas é uma técnica de pintura?", "opcoes": ["Aquarela", "Biologia", "História", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destes é um famoso pintor?", "opcoes": ["Van Gogh", "Einstein", "Newton", "Edison"], "resposta": 0},
            {"pergunta": "Qual destas é uma forma de arte?", "opcoes": ["Escultura", "Cálculo", "Análise", "Pesquisa"], "resposta": 0},
        ]
    },
    "9° Ano": {
        "Matemática": [
            {"pergunta": "Quanto é 348 + 567?", "opcoes": ["914", "915", "916", "917"], "resposta": 2},
            {"pergunta": "Quanto é 725 - 418?", "opcoes": ["306", "307", "308", "309"], "resposta": 3},
            {"pergunta": "Quanto é 34 x 15?", "opcoes": ["509", "510", "511", "512"], "resposta": 1},
            {"pergunta": "Quanto é 512 ÷ 8?", "opcoes": ["62", "63", "64", "65"], "resposta": 2},
            {"pergunta": "Qual é a raiz quadrada de 144?", "opcoes": ["10", "11", "12", "13"], "resposta": 2},
            {"pergunta": "Quanto é 14²?", "opcoes": ["194", "195", "196", "197"], "resposta": 2},
            {"pergunta": "Qual é a área de um retângulo de lados 8 e 12?", "opcoes": ["94", "95", "96", "97"], "resposta": 2},
            {"pergunta": "Quanto é 64 x 4?", "opcoes": ["254", "255", "256", "257"], "resposta": 2},
            {"pergunta": "Quanto é 192 ÷ 6?", "opcoes": ["30", "31", "32", "33"], "resposta": 2},
            {"pergunta": "Qual é o perímetro de um triângulo de lados 5, 12 e 13?", "opcoes": ["28", "29", "30", "31"], "resposta": 2},
        ],
        "Língua Portuguesa": [
            {"pergunta": "Qual é o sinônimo de 'audaz'?", "opcoes": ["Covarde", "Valente", "Medroso", "Preguiçoso"], "resposta": 1},
            {"pergunta": "Qual é o antônimo de 'paz'?", "opcoes": ["Tranquilidade", "Guerra", "Calma", "Harmonia"], "resposta": 1},
            {"pergunta": "Qual é o coletivo de 'cão'?", "opcoes": ["Matilha", "Rebanho", "Bando", "Alcateia"], "resposta": 0},
            {"pergunta": "Qual é o diminutivo de 'livro'?", "opcoes": ["Livrote", "Livrinho", "Livrões", "Livretos"], "resposta": 1},
            {"pergunta": "Qual é o feminino de 'rei'?", "opcoes": ["Rei", "Rainha", "Reis", "Reia"], "resposta": 1},
            {"pergunta": "Qual é a forma correta do verbo 'fazer' no futuro do presente?", "opcoes": ["Faria", "Faço", "Farei", "Fazer"], "resposta": 2},
            {"pergunta": "Qual é o tempo verbal da frase 'Nós estudaremos amanhã'?", "opcoes": ["Presente", "Pretérito", "Futuro", "Gerúndio"], "resposta": 2},
            {"pergunta": "Qual é a forma correta de conjugação do verbo 'vir' na primeira pessoa do singular no presente?", "opcoes": ["Vem", "Vens", "Venho", "Vim"], "resposta": 2},
            {"pergunta": "Qual é a forma correta do plural de 'pão'?", "opcoes": ["Pães", "Pãos", "Pãozes", "Pãozões"], "resposta": 0},
            {"pergunta": "Qual é o verbo da frase 'Eles escreverão o relatório'?", "opcoes": ["Eles", "Escreverão", "O", "Relatório"], "resposta": 1},
        ],
        "Ciências": [
            {"pergunta": "Qual é o principal componente da água?", "opcoes": ["Hidrogênio", "Oxigênio", "Nitrogênio", "Carbono"], "resposta": 0},
            {"pergunta": "Qual é a função do coração?", "opcoes": ["Respirar", "Bombear sangue", "Digestão", "Mastigação"], "resposta": 1},
            {"pergunta": "Qual é o processo de conversão de água em vapor?", "opcoes": ["Condensação", "Evaporação", "Sublimação", "Solidificação"], "resposta": 1},
            {"pergunta": "Qual destes é um exemplo de fonte de energia renovável?", "opcoes": ["Carvão", "Petróleo", "Vento", "Gás natural"], "resposta": 2},
            {"pergunta": "Qual é o planeta mais próximo do Sol?", "opcoes": ["Marte", "Terra", "Vênus", "Mercúrio"], "resposta": 3},
            {"pergunta": "Qual é o maior animal terrestre?", "opcoes": ["Elefante", "Girafa", "Rinoceronte", "Hipopótamo"], "resposta": 0},
            {"pergunta": "Qual é o processo pelo qual as plantas produzem oxigênio?", "opcoes": ["Fotossíntese", "Respiração", "Transpiração", "Digestão"], "resposta": 0},
            {"pergunta": "Qual é o estado físico da água a 0°C?", "opcoes": ["Líquido", "Sólido", "Gasoso", "Plasma"], "resposta": 1},
            {"pergunta": "Qual é a principal função dos rins?", "opcoes": ["Bombear sangue", "Filtrar sangue", "Respiração", "Digestão"], "resposta": 1},
            {"pergunta": "Qual é a unidade básica da vida?", "opcoes": ["Célula", "Átomo", "Molécula", "Organismo"], "resposta": 0},
        ],
        "História": [
            {"pergunta": "Quem foi o primeiro presidente do Brasil?", "opcoes": ["Getúlio Vargas", "Juscelino Kubitschek", "Deodoro da Fonseca", "Dom Pedro II"], "resposta": 2},
            {"pergunta": "Quem proclamou a independência do Brasil?", "opcoes": ["Dom Pedro I", "Dom Pedro II", "Tiradentes", "Deodoro da Fonseca"], "resposta": 0},
            {"pergunta": "Quem descobriu o Brasil?", "opcoes": ["Cristóvão Colombo", "Pedro Álvares Cabral", "Vasco da Gama", "Fernão de Magalhães"], "resposta": 1},
            {"pergunta": "O que foram as capitanias hereditárias?", "opcoes": ["Divisões administrativas no Brasil Colônia", "Tipos de plantações", "Grupos de indígenas", "Territórios na África"], "resposta": 0},
            {"pergunta": "Quem foi Tiradentes?", "opcoes": ["Um pintor", "Um médico", "Um dentista e herói da Inconfidência Mineira", "Um presidente"], "resposta": 2},
            {"pergunta": "Quem foi Zumbi dos Palmares?", "opcoes": ["Um líder indígena", "Um líder dos escravos", "Um presidente", "Um artista"], "resposta": 1},
            {"pergunta": "O que é uma aldeia indígena?", "opcoes": ["Um grupo de animais", "Um grupo de casas onde vivem indígenas", "Uma cidade grande", "Um tipo de planta"], "resposta": 1},
            {"pergunta": "O que é um museu?", "opcoes": ["Um lugar onde se guardam objetos históricos", "Uma escola", "Um hospital", "Um parque"], "resposta": 0},
            {"pergunta": "Quem foi o líder da Revolução Francesa?", "opcoes": ["Napoleão Bonaparte", "Louis XVI", "Robespierre", "Voltaire"], "resposta": 2},
            {"pergunta": "Quem foi o imperador romano conhecido por sua crueldade?", "opcoes": ["César", "Augusto", "Nero", "Trajano"], "resposta": 2},
        ],
        "Geografia": [
            {"pergunta": "Qual é o maior país da América do Sul?", "opcoes": ["Argentina", "Brasil", "Chile", "Peru"], "resposta": 1},
            {"pergunta": "Qual é o rio mais longo do mundo?", "opcoes": ["Nilo", "Amazonas", "Mississipi", "Yangtze"], "resposta": 0},
            {"pergunta": "Qual é a capital do Brasil?", "opcoes": ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], "resposta": 2},
            {"pergunta": "Qual é o maior continente?", "opcoes": ["África", "América", "Ásia", "Europa"], "resposta": 2},
            {"pergunta": "Qual é o menor continente?", "opcoes": ["África", "Oceania", "Antártica", "Europa"], "resposta": 1},
            {"pergunta": "Qual é o maior oceano?", "opcoes": ["Atlântico", "Pacífico", "Índico", "Ártico"], "resposta": 1},
            {"pergunta": "Qual é a maior floresta tropical do mundo?", "opcoes": ["Floresta Amazônica", "Floresta Negra", "Floresta de Sherwood", "Floresta de Borneo"], "resposta": 0},
            {"pergunta": "Qual país tem a maior população do mundo?", "opcoes": ["Índia", "Estados Unidos", "China", "Brasil"], "resposta": 2},
            {"pergunta": "Qual é a maior montanha do mundo?", "opcoes": ["Monte Everest", "K2", "Kangchenjunga", "Lhotse"], "resposta": 0},
            {"pergunta": "Qual é a capital da França?", "opcoes": ["Londres", "Paris", "Berlim", "Roma"], "resposta": 1},
        ],
        "Computação": [
            {"pergunta": "O que é um software?", "opcoes": ["Um programa de computador", "Um hardware", "Um periférico", "Um sistema operacional"], "resposta": 0},
            {"pergunta": "Qual desses dispositivos é de entrada?", "opcoes": ["Monitor", "Impressora", "Teclado", "CPU"], "resposta": 2},
            {"pergunta": "Para que serve o mouse?", "opcoes": ["Digitar", "Selecionar itens na tela", "Armazenar dados", "Exibir imagens"], "resposta": 1},
            {"pergunta": "O que é um vírus de computador?", "opcoes": ["Um hardware", "Um software malicioso", "Um sistema operacional", "Um navegador"], "resposta": 1},
            {"pergunta": "Qual dispositivo usamos para digitar?", "opcoes": ["Mouse", "Teclado", "Monitor", "Impressora"], "resposta": 1},
            {"pergunta": "Qual parte do computador mostra as imagens?", "opcoes": ["Mouse", "Teclado", "Monitor", "CPU"], "resposta": 2},
            {"pergunta": "Qual parte do computador armazena informações?", "opcoes": ["Monitor", "Teclado", "Mouse", "HD"], "resposta": 3},
            {"pergunta": "Qual desses é um navegador de internet?", "opcoes": ["Windows", "Word", "Chrome", "Excel"], "resposta": 2},
            {"pergunta": "O que significa a sigla 'CPU'?", "opcoes": ["Central Processing Unit", "Computer Personal Unit", "Central Personal Unit", "Computer Processing Unit"], "resposta": 0},
            {"pergunta": "Qual desses é um sistema operacional?", "opcoes": ["Microsoft Word", "Google Chrome", "Windows", "Excel"], "resposta": 2},
        ],
        "Arte": [
            {"pergunta": "Qual destas é uma cor primária?", "opcoes": ["Verde", "Amarelo", "Roxo", "Laranja"], "resposta": 1},
            {"pergunta": "Qual destes é um material usado para desenhar?", "opcoes": ["Papel", "Lápis", "Tesoura", "Cola"], "resposta": 1},
            {"pergunta": "Qual destes é um artista famoso?", "opcoes": ["Leonardo da Vinci", "Isaac Newton", "Albert Einstein", "Galileu Galilei"], "resposta": 0},
            {"pergunta": "Qual destes é um estilo de dança?", "opcoes": ["Ballet", "Cálculo", "Geometria", "Física"], "resposta": 0},
            {"pergunta": "Qual destes é um instrumento musical?", "opcoes": ["Violino", "Bola", "Livro", "Computador"], "resposta": 0},
            {"pergunta": "O que usamos para pintar?", "opcoes": ["Pincel", "Cola", "Tesoura", "Borracha"], "resposta": 0},
            {"pergunta": "Qual destes é um gênero musical?", "opcoes": ["Rock", "Física", "Matemática", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destas é uma técnica de pintura?", "opcoes": ["Aquarela", "Biologia", "História", "Geografia"], "resposta": 0},
            {"pergunta": "Qual destes é um famoso pintor?", "opcoes": ["Van Gogh", "Einstein", "Newton", "Edison"], "resposta": 0},
            {"pergunta": "Qual destas é uma forma de arte?", "opcoes": ["Escultura", "Cálculo", "Análise", "Pesquisa"], "resposta": 0},
        ]
    }
}
